server:
  port: 7084      #springboot端口

tcp:
  backlog: 1024
  keepalive: true
  noDelay: false


netty:
  port: 7000    #netty端口
  context-path: /groupchat   #netty访问路径（和前端保持一致）

spring:
  application:
    name: groupchat
  #   数据源基本配置
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/danmu?characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  # redis配置
  redis:
    #服务器地址
    host: localhost
    #端口
    port: 6379
    #数据库
    database: 0
    #超时时间
    timeout: 10000ms
    #密码
    # password: 123456
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 5
  # rabbit
#  rabbitmq:
#    host: localhost
#    username: guest
#    password: guest
#    virtual-host: /
#    port: 5672
#    listener:
#      simple:
#        # 消费者的最小数量
#        concurrency: 10
#        # 消费者的最大数量
#        max-concurrency: 20
#        # 限制消费者，每次处理一条消息
#        prefetch: 1
#        # 启动时默认启动容器
#        auto-startup: true
#        # 被拒绝时是否重新入队
#        default-requeue-rejected: true
#    template:
#      retry:
#        #发布重试，默认false
#        enabled: true
#        #重试时间，默认1000ms
#        initial-interval: 1000ms
#        #重试最大次数，默认3次
#        max-attempts: 3
#        #重试最大间隔时间，默认10000ms
#        max-interval: 10000ms
#        #重试的间隔乘数。比如配2.0，第一次就等10s，第二次就等20s，第三次就等40s
#        multiplier: 1
  # kafka
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      auto-commit-interval: 100
      auto-offset-reset: latest
      enable-auto-commit: false
      group-id: mygroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1000
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 1
      poll-timeout: 1000
      type: batch

#mybatis
mybatis-plus:

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  mapper-locations: classpath*:/mapper/*Mapper.xml


